import {Product, Allergen, Diet} from "../product.types";

export const products: Product[] = [
  {
    uid: "okt0",
    name: "Oktopus",
    department: {uid: "tk", name: "Tiefkühl"},
    shoppingUnit: "kg",
    dietProperties: {allergens: [], diet: Diet.Meat},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
  {
    uid: "mozza",
    name: "Mozzarella",
    department: {uid: "molk", name: "Molkerei"},
    shoppingUnit: "kg",
    dietProperties: {allergens: [Allergen.Lactose], diet: Diet.Vegetarian},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
  {
    uid: "n0r!",
    name: "Nori",
    department: {uid: "arigato", name: "Fremdländische Spezialitäten"},
    shoppingUnit: "g",
    dietProperties: {allergens: [], diet: Diet.Vegan},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
  {
    uid: "g1ng3",
    name: "Ingwer",
    department: {uid: "vegetable", name: "Gemüse"},
    shoppingUnit: "g",
    dietProperties: {allergens: [], diet: Diet.Vegan},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
  {
    uid: "soys0ce",
    name: "Sojasauce",
    department: {uid: "orient", name: "Fremdländische Spezialitäten"},
    shoppingUnit: "l",
    dietProperties: {allergens: [Allergen.Gluten], diet: Diet.Vegan},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
  {
    uid: "t4hini",
    name: "Tahini",
    department: {uid: "convenience", name: "Convenience"},
    shoppingUnit: "kg",
    dietProperties: {allergens: [], diet: Diet.Vegan},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
  {
    uid: "h0n3y",
    name: "Honig",
    department: {uid: "breakfast", name: "Frühstück"},
    shoppingUnit: "kg",
    dietProperties: {allergens: [], diet: Diet.Vegetarian},
    usable: true,
    qaChecked: false,
    qaCheckedAt: null,
  },
];
export default products;
