server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Content Security Policy
    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self';
        connect-src 'self'
            https://api.chuchipirat.ch
            wss://api.chuchipirat.ch
            https://o4508411678425088.ingest.de.sentry.io
            https://umami.chuchipirat.ch
            https://firebasestorage.googleapis.com;
        img-src 'self' data: blob: https:;
        style-src 'self' 'unsafe-inline';
        font-src 'self' data:;
        frame-ancestors 'none';
    " always;

    # Weitere Security Headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
