-- =============================================================================
-- Chuchipirat – Baseline Migration (2/7): Tables
-- Generated: 2026-04-01
-- =============================================================================
-- This file is part of the baseline schema. Do NOT modify after first deploy.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Auth & Users
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.users (
    id uuid NOT NULL,
    email text NOT NULL,
    first_name text DEFAULT ''::text NOT NULL CONSTRAINT chk_first_name_length CHECK (char_length(first_name) <= 100),
    last_name text DEFAULT ''::text NOT NULL CONSTRAINT chk_last_name_length CHECK (char_length(last_name) <= 100),
    roles public.user_role[] DEFAULT ARRAY['basic'::public.user_role] NOT NULL,
    no_logins integer DEFAULT 0 NOT NULL,
    display_name text DEFAULT ''::text NOT NULL CONSTRAINT chk_display_name_length CHECK (char_length(display_name) <= 100),
    member_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    motto text DEFAULT ''::text NOT NULL CONSTRAINT chk_motto_length CHECK (char_length(motto) <= 500),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    search_vector tsvector GENERATED ALWAYS AS (
      to_tsvector('german'::regconfig,
        COALESCE(display_name, '') || ' ' ||
        COALESCE(email, '') || ' ' ||
        COALESCE(first_name, '') || ' ' ||
        COALESCE(last_name, '')
      )
    ) STORED,
    picture_src text DEFAULT ''::text NOT NULL,
    no_found_bugs integer DEFAULT 0 NOT NULL,
    legacy_firebase_uid text,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT fk_users_auth FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Global Config
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.global_settings (
    id text DEFAULT 'default'::text NOT NULL,
    allow_sign_up boolean DEFAULT false NOT NULL,
    maintenance_mode boolean DEFAULT false NOT NULL,
    email_lookup_rate_limit integer DEFAULT 10 NOT NULL,
    redirect_emails_to_mailpit boolean DEFAULT false NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT global_settings_pkey PRIMARY KEY (id),
    CONSTRAINT single_row CHECK (id = 'default'::text),
    CONSTRAINT global_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT global_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.global_settings ENABLE ROW LEVEL SECURITY;

-- Singleton-Zeile einfügen (wird von der App per UPDATE aktualisiert)
INSERT INTO public.global_settings (id) VALUES ('default') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.system_messages (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    text text DEFAULT ''::text NOT NULL,
    type text DEFAULT 'info'::text NOT NULL,
    valid_to timestamptz DEFAULT now() NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT system_messages_pkey PRIMARY KEY (id),
    CONSTRAINT system_messages_type_check CHECK (type = ANY (ARRAY['success', 'info', 'warning', 'error'])),
    CONSTRAINT system_messages_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT system_messages_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.system_messages ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Masterdata
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.departments (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    name text DEFAULT ''::text NOT NULL,
    pos integer DEFAULT 0 NOT NULL,
    usable boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT departments_pkey PRIMARY KEY (id),
    CONSTRAINT departments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT departments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.units (
    key text NOT NULL,
    firebase_uid text,
    name text DEFAULT ''::text NOT NULL,
    dimension text DEFAULT 'DLS'::text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT units_pkey PRIMARY KEY (key),
    CONSTRAINT units_dimension_check CHECK (dimension = ANY (ARRAY['VOL', 'MAS', 'DLS'])),
    CONSTRAINT units_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT units_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Products & Materials
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.products (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    name text DEFAULT ''::text NOT NULL,
    name_singular text DEFAULT ''::text NOT NULL,
    department_id text,
    shopping_unit text,
    allergens public.allergen_type[] DEFAULT '{}'::public.allergen_type[] NOT NULL,
    diet public.diet_type DEFAULT 'meat'::public.diet_type NOT NULL,
    usable boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    qa_checked boolean DEFAULT false NOT NULL,
    qa_checked_at timestamptz,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL,
    CONSTRAINT products_shopping_unit_fkey FOREIGN KEY (shopping_unit) REFERENCES public.units(key) ON DELETE SET NULL,
    CONSTRAINT products_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.products IS 'Stammdaten-Tabelle für Produkte';
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.materials (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    name text DEFAULT ''::text NOT NULL,
    type public.material_type DEFAULT 'consumable'::public.material_type NOT NULL,
    usable boolean DEFAULT true NOT NULL,
    qa_checked boolean DEFAULT false NOT NULL,
    qa_checked_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT materials_pkey PRIMARY KEY (id),
    CONSTRAINT materials_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT materials_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.unit_conversion_basic (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    from_unit text NOT NULL,
    to_unit text NOT NULL,
    numerator integer DEFAULT 1 NOT NULL,
    denominator integer DEFAULT 1 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT unit_conversion_basic_pkey PRIMARY KEY (id),
    CONSTRAINT unit_conversion_basic_from_unit_fkey FOREIGN KEY (from_unit) REFERENCES public.units(key) ON DELETE CASCADE,
    CONSTRAINT unit_conversion_basic_to_unit_fkey FOREIGN KEY (to_unit) REFERENCES public.units(key) ON DELETE CASCADE,
    CONSTRAINT unit_conversion_basic_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT unit_conversion_basic_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.unit_conversion_basic ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.unit_conversion_products (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    from_unit text NOT NULL,
    to_unit text NOT NULL,
    numerator integer DEFAULT 1 NOT NULL,
    denominator integer DEFAULT 1 NOT NULL,
    product_id text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT unit_conversion_products_pkey PRIMARY KEY (id),
    CONSTRAINT unit_conversion_products_from_unit_fkey FOREIGN KEY (from_unit) REFERENCES public.units(key) ON DELETE CASCADE,
    CONSTRAINT unit_conversion_products_to_unit_fkey FOREIGN KEY (to_unit) REFERENCES public.units(key) ON DELETE CASCADE,
    CONSTRAINT unit_conversion_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE,
    CONSTRAINT unit_conversion_products_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT unit_conversion_products_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.unit_conversion_products ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_synonyms (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    name_a text NOT NULL,
    name_b text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT product_synonyms_pkey PRIMARY KEY (id),
    CONSTRAINT product_synonyms_name_a_name_b_key UNIQUE (name_a, name_b),
    CONSTRAINT product_synonyms_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT product_synonyms_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.product_synonyms ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.product_duplicate_dismissals (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    product_a_id text NOT NULL,
    product_b_id text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT product_duplicate_dismissals_pkey PRIMARY KEY (id),
    CONSTRAINT uq_dismissal_pair UNIQUE (product_a_id, product_b_id),
    CONSTRAINT chk_normalized_order CHECK (product_a_id < product_b_id),
    CONSTRAINT product_duplicate_dismissals_product_a_id_fkey FOREIGN KEY (product_a_id) REFERENCES public.products(id) ON DELETE CASCADE,
    CONSTRAINT product_duplicate_dismissals_product_b_id_fkey FOREIGN KEY (product_b_id) REFERENCES public.products(id) ON DELETE CASCADE,
    CONSTRAINT product_duplicate_dismissals_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT product_duplicate_dismissals_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.product_duplicate_dismissals ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Recipes
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.recipes (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    name text DEFAULT ''::text NOT NULL CONSTRAINT chk_recipe_name_length CHECK (char_length(name) <= 200),
    portions integer DEFAULT 0 NOT NULL,
    source text DEFAULT ''::text NOT NULL CONSTRAINT chk_recipe_source_length CHECK (char_length(source) <= 500),
    time_preparation integer DEFAULT 0 NOT NULL,
    time_rest integer DEFAULT 0 NOT NULL,
    time_cooking integer DEFAULT 0 NOT NULL,
    picture_src text DEFAULT ''::text NOT NULL,
    note text DEFAULT ''::text NOT NULL CONSTRAINT chk_recipe_note_length CHECK (char_length(note) <= 2000),
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    menu_types public.menu_type[] DEFAULT '{}'::public.menu_type[] NOT NULL,
    diet public.diet_type DEFAULT 'meat'::public.diet_type NOT NULL,
    allergens public.allergen_type[] DEFAULT '{}'::public.allergen_type[] NOT NULL,
    outdoor_kitchen_suitable boolean DEFAULT false NOT NULL,
    is_in_review boolean DEFAULT false NOT NULL,
    usable boolean DEFAULT true NOT NULL,
    avg_rating numeric(3,2) DEFAULT 0 NOT NULL,
    no_ratings integer DEFAULT 0 NOT NULL,
    recipe_type public.recipe_type DEFAULT 'public'::public.recipe_type NOT NULL,
    variant_note text,
    variant_name text,
    variant_event_uid text,
    original_recipe_uid text,
    original_recipe_type public.recipe_type,
    original_recipe_creator_uid text,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    no_comments integer DEFAULT 0 NOT NULL,
    CONSTRAINT recipes_pkey PRIMARY KEY (id),
    CONSTRAINT recipes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT recipes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);
-- FKs to events and self-reference added after events table below

ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.recipe_ingredients (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    recipe_id text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    pos_type public.recipe_ingredient_pos_type DEFAULT 'ingredient'::public.recipe_ingredient_pos_type NOT NULL,
    product_id text,
    quantity numeric(12,4) DEFAULT 0 NOT NULL,
    unit text,
    detail text DEFAULT ''::text NOT NULL,
    scaling_factor numeric(8,4) DEFAULT 1 NOT NULL,
    section_name text DEFAULT ''::text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT recipe_ingredients_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_ingredients_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE,
    CONSTRAINT recipe_ingredients_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL,
    CONSTRAINT recipe_ingredients_unit_fkey FOREIGN KEY (unit) REFERENCES public.units(key) ON DELETE SET NULL,
    CONSTRAINT recipe_ingredients_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT recipe_ingredients_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.recipe_ingredients ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.recipe_preparation_steps (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    recipe_id text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    pos_type public.recipe_step_pos_type DEFAULT 'preparation_step'::public.recipe_step_pos_type NOT NULL,
    step text DEFAULT ''::text NOT NULL,
    section_name text DEFAULT ''::text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT recipe_preparation_steps_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_preparation_steps_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE,
    CONSTRAINT recipe_preparation_steps_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT recipe_preparation_steps_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.recipe_preparation_steps ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.recipe_materials (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    recipe_id text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    material_id text,
    quantity numeric(12,4) DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT recipe_materials_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_materials_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE,
    CONSTRAINT recipe_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE SET NULL,
    CONSTRAINT recipe_materials_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT recipe_materials_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.recipe_materials ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.recipe_ratings (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    recipe_id text NOT NULL,
    user_id uuid NOT NULL,
    rating integer NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT recipe_ratings_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_ratings_recipe_id_user_id_key UNIQUE (recipe_id, user_id),
    CONSTRAINT recipe_ratings_rating_check CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT recipe_ratings_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE,
    CONSTRAINT recipe_ratings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT recipe_ratings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT recipe_ratings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.recipe_ratings ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.recipe_comments (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    recipe_id text NOT NULL,
    comment text DEFAULT ''::text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT recipe_comments_pkey PRIMARY KEY (id),
    CONSTRAINT recipe_comments_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE CASCADE,
    CONSTRAINT recipe_comments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT recipe_comments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.recipe_comments ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Events (core)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.events (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    name text DEFAULT ''::text NOT NULL CONSTRAINT chk_event_name_length CHECK (char_length(name) <= 200),
    motto text DEFAULT ''::text NOT NULL CONSTRAINT chk_event_motto_length CHECK (char_length(motto) <= 500),
    location text DEFAULT ''::text NOT NULL CONSTRAINT chk_event_location_length CHECK (char_length(location) <= 200),
    picture_src text DEFAULT ''::text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT events_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.events REPLICA IDENTITY FULL;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- Now add deferred FKs on recipes that reference events
ALTER TABLE public.recipes
  ADD CONSTRAINT fk_recipes_variant_event FOREIGN KEY (variant_event_uid) REFERENCES public.events(id) ON DELETE CASCADE;
ALTER TABLE public.recipes
  ADD CONSTRAINT fk_recipes_original_recipe FOREIGN KEY (original_recipe_uid) REFERENCES public.recipes(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.event_cooks (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    user_id uuid NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_cooks_pkey PRIMARY KEY (id),
    CONSTRAINT event_cooks_event_id_user_id_key UNIQUE (event_id, user_id),
    CONSTRAINT event_cooks_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_cooks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT event_cooks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_cooks_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_cooks REPLICA IDENTITY FULL;
ALTER TABLE public.event_cooks ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_dates (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    date_from date NOT NULL,
    date_to date NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_dates_pkey PRIMARY KEY (id),
    CONSTRAINT event_dates_check CHECK (date_from <= date_to),
    CONSTRAINT event_dates_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_dates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_dates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_dates REPLICA IDENTITY FULL;
ALTER TABLE public.event_dates ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_groupconfiguration_diets (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_groupconfiguration_diets_pkey PRIMARY KEY (id),
    CONSTRAINT event_groupconfiguration_diets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_groupconfiguration_diets_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_groupconfiguration_diets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_groupconfiguration_diets REPLICA IDENTITY FULL;
ALTER TABLE public.event_groupconfiguration_diets ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_groupconfiguration_intolerances (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_groupconfiguration_intolerances_pkey PRIMARY KEY (id),
    CONSTRAINT event_groupconfiguration_intolerances_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_groupconfiguration_intolerances_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_groupconfiguration_intolerances_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_groupconfiguration_intolerances REPLICA IDENTITY FULL;
ALTER TABLE public.event_groupconfiguration_intolerances ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_groupconfiguration_portions (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    diet_id text NOT NULL,
    intolerance_id text NOT NULL,
    servings integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_groupconfiguration_portions_pkey PRIMARY KEY (id),
    CONSTRAINT event_groupconfiguration_port_event_id_diet_id_intolerance__key UNIQUE (event_id, diet_id, intolerance_id),
    CONSTRAINT event_groupconfiguration_portions_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_groupconfiguration_portions_diet_id_fkey FOREIGN KEY (diet_id) REFERENCES public.event_groupconfiguration_diets(id) ON DELETE CASCADE,
    CONSTRAINT event_groupconfiguration_portions_intolerance_id_fkey FOREIGN KEY (intolerance_id) REFERENCES public.event_groupconfiguration_intolerances(id) ON DELETE CASCADE,
    CONSTRAINT event_groupconfiguration_portions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_groupconfiguration_portions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_groupconfiguration_portions REPLICA IDENTITY FULL;
ALTER TABLE public.event_groupconfiguration_portions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_meal_types (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT event_meal_types_pkey PRIMARY KEY (id),
    CONSTRAINT event_meal_types_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE
);

ALTER TABLE public.event_meal_types REPLICA IDENTITY FULL;
ALTER TABLE public.event_meal_types ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_meals (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    meal_date date NOT NULL,
    meal_type_id text NOT NULL,
    CONSTRAINT event_meals_pkey PRIMARY KEY (id),
    CONSTRAINT event_meals_event_id_meal_date_meal_type_id_key UNIQUE (event_id, meal_date, meal_type_id),
    CONSTRAINT event_meals_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_meals_meal_type_id_fkey FOREIGN KEY (meal_type_id) REFERENCES public.event_meal_types(id) ON DELETE CASCADE
);

ALTER TABLE public.event_meals REPLICA IDENTITY FULL;
ALTER TABLE public.event_meals ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_menues (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    meal_id text NOT NULL,
    name text DEFAULT ''::text NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT event_menues_pkey PRIMARY KEY (id),
    CONSTRAINT event_menues_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_menues_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.event_meals(id) ON DELETE CASCADE
);

ALTER TABLE public.event_menues REPLICA IDENTITY FULL;
ALTER TABLE public.event_menues ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_menue_recipes (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    menue_id text NOT NULL,
    recipe_id text,
    deleted_recipe_name text,
    variant_name text,
    total_portions numeric(10,2) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT event_menue_recipes_pkey PRIMARY KEY (id),
    CONSTRAINT chk_menue_recipes_total_portions_non_negative CHECK (total_portions >= 0),
    CONSTRAINT event_menue_recipes_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_menue_recipes_menue_id_fkey FOREIGN KEY (menue_id) REFERENCES public.event_menues(id) ON DELETE CASCADE,
    CONSTRAINT event_menue_recipes_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes(id) ON DELETE RESTRICT
);

ALTER TABLE public.event_menue_recipes REPLICA IDENTITY FULL;
ALTER TABLE public.event_menue_recipes ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_menue_products (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    menue_id text NOT NULL,
    product_id text NOT NULL,
    quantity numeric(12,4) DEFAULT 0 NOT NULL,
    unit text,
    plan_mode public.plan_mode_type DEFAULT 'total'::public.plan_mode_type NOT NULL,
    total_quantity numeric(12,4) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT event_menue_products_pkey PRIMARY KEY (id),
    CONSTRAINT chk_menue_products_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT event_menue_products_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_menue_products_menue_id_fkey FOREIGN KEY (menue_id) REFERENCES public.event_menues(id) ON DELETE CASCADE,
    CONSTRAINT event_menue_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT,
    CONSTRAINT event_menue_products_unit_fkey FOREIGN KEY (unit) REFERENCES public.units(key) ON DELETE SET NULL
);

ALTER TABLE public.event_menue_products REPLICA IDENTITY FULL;
ALTER TABLE public.event_menue_products ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_menue_materials (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    menue_id text NOT NULL,
    material_id text NOT NULL,
    quantity numeric(12,4) DEFAULT 0 NOT NULL,
    unit text,
    plan_mode public.plan_mode_type DEFAULT 'total'::public.plan_mode_type NOT NULL,
    total_quantity numeric(12,4) DEFAULT 0 NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT event_menue_materials_pkey PRIMARY KEY (id),
    CONSTRAINT chk_menue_materials_quantity_non_negative CHECK (quantity >= 0),
    CONSTRAINT event_menue_materials_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_menue_materials_menue_id_fkey FOREIGN KEY (menue_id) REFERENCES public.event_menues(id) ON DELETE CASCADE,
    CONSTRAINT event_menue_materials_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE RESTRICT,
    CONSTRAINT event_menue_materials_unit_fkey FOREIGN KEY (unit) REFERENCES public.units(key) ON DELETE SET NULL
);

ALTER TABLE public.event_menue_materials REPLICA IDENTITY FULL;
ALTER TABLE public.event_menue_materials ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_notes (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    event_id text NOT NULL,
    menue_id text,
    note_date date NOT NULL,
    text text DEFAULT ''::text NOT NULL,
    CONSTRAINT event_notes_pkey PRIMARY KEY (id),
    CONSTRAINT event_notes_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_notes_menue_id_fkey FOREIGN KEY (menue_id) REFERENCES public.event_menues(id) ON DELETE CASCADE
);

ALTER TABLE public.event_notes REPLICA IDENTITY FULL;
ALTER TABLE public.event_notes ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_menuplan_item_plans (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    event_id text NOT NULL,
    menue_recipe_id text,
    menue_product_id text,
    menue_material_id text,
    diet_scope public.plan_scope_type DEFAULT 'ALL'::public.plan_scope_type NOT NULL,
    diet_id text,
    intolerance_scope public.plan_scope_type DEFAULT 'ALL'::public.plan_scope_type NOT NULL,
    intolerance_id text,
    factor numeric(10,4) DEFAULT 1 NOT NULL,
    servings numeric(10,2) DEFAULT 0 NOT NULL,
    CONSTRAINT event_menuplan_item_plans_pkey PRIMARY KEY (id),
    CONSTRAINT chk_item_plans_factor_non_negative CHECK (factor >= 0),
    CONSTRAINT chk_item_plans_servings_non_negative CHECK (servings >= 0),
    CONSTRAINT event_menuplan_item_plans_check CHECK ((diet_scope <> 'group'::plan_scope_type) OR (diet_id IS NOT NULL)),
    CONSTRAINT event_menuplan_item_plans_check1 CHECK ((intolerance_scope <> 'group'::plan_scope_type) OR (intolerance_id IS NOT NULL)),
    CONSTRAINT event_menuplan_item_plans_check2 CHECK (((menue_recipe_id IS NOT NULL)::integer + (menue_product_id IS NOT NULL)::integer + (menue_material_id IS NOT NULL)::integer) = 1),
    CONSTRAINT event_menuplan_item_plans_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_menuplan_item_plans_menue_recipe_id_fkey FOREIGN KEY (menue_recipe_id) REFERENCES public.event_menue_recipes(id) ON DELETE CASCADE,
    CONSTRAINT event_menuplan_item_plans_menue_product_id_fkey FOREIGN KEY (menue_product_id) REFERENCES public.event_menue_products(id) ON DELETE CASCADE,
    CONSTRAINT event_menuplan_item_plans_menue_material_id_fkey FOREIGN KEY (menue_material_id) REFERENCES public.event_menue_materials(id) ON DELETE CASCADE,
    CONSTRAINT event_menuplan_item_plans_diet_id_fkey FOREIGN KEY (diet_id) REFERENCES public.event_groupconfiguration_diets(id) ON DELETE CASCADE,
    CONSTRAINT event_menuplan_item_plans_intolerance_id_fkey FOREIGN KEY (intolerance_id) REFERENCES public.event_groupconfiguration_intolerances(id) ON DELETE CASCADE
);

ALTER TABLE public.event_menuplan_item_plans REPLICA IDENTITY FULL;
ALTER TABLE public.event_menuplan_item_plans ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_menuplan_tracking (
    event_id text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_menuplan_tracking_pkey PRIMARY KEY (event_id),
    CONSTRAINT event_menuplan_tracking_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_menuplan_tracking_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_menuplan_tracking_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_menuplan_tracking REPLICA IDENTITY FULL;
ALTER TABLE public.event_menuplan_tracking ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Used Recipe Lists
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.event_used_recipe_lists (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    event_id text NOT NULL,
    name text NOT NULL,
    firebase_uid text,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    selected_menue_ids text[] DEFAULT '{}'::text[] NOT NULL,
    selected_meal_ids text[] DEFAULT '{}'::text[] NOT NULL,
    CONSTRAINT event_used_recipe_lists_pkey PRIMARY KEY (id),
    CONSTRAINT event_used_recipe_lists_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_used_recipe_lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_used_recipe_lists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_used_recipe_lists ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. Shopping Lists
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.event_shopping_lists (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    event_id text NOT NULL,
    name text NOT NULL,
    selected_menues text[] DEFAULT '{}'::text[] NOT NULL,
    selected_meals text[] DEFAULT '{}'::text[] NOT NULL,
    selected_departments text[] DEFAULT '{}'::text[] NOT NULL,
    has_manually_added_items boolean DEFAULT false NOT NULL,
    firebase_uid text,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_shopping_lists_pkey PRIMARY KEY (id),
    CONSTRAINT event_shopping_lists_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_shopping_lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_shopping_lists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_shopping_lists REPLICA IDENTITY FULL;
ALTER TABLE public.event_shopping_lists ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_shopping_list_items (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    list_id text NOT NULL,
    product_id text,
    material_id text,
    department_id text,
    free_text_name text CONSTRAINT chk_free_text_name_length CHECK (char_length(free_text_name) <= 200),
    quantity numeric DEFAULT 0 NOT NULL,
    unit text,
    checked boolean DEFAULT false NOT NULL,
    edit_source public.shopping_list_edit_source DEFAULT 'generated'::public.shopping_list_edit_source NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_shopping_list_items_pkey PRIMARY KEY (id),
    CONSTRAINT chk_item_source CHECK (
      (product_id IS NOT NULL AND material_id IS NULL AND free_text_name IS NULL) OR
      (product_id IS NULL AND material_id IS NOT NULL AND free_text_name IS NULL) OR
      (product_id IS NULL AND material_id IS NULL AND free_text_name IS NOT NULL)
    ),
    CONSTRAINT event_shopping_list_items_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.event_shopping_lists(id) ON DELETE CASCADE,
    CONSTRAINT event_shopping_list_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL,
    CONSTRAINT event_shopping_list_items_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE SET NULL,
    CONSTRAINT event_shopping_list_items_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE SET NULL,
    CONSTRAINT event_shopping_list_items_unit_fkey FOREIGN KEY (unit) REFERENCES public.units(key) ON DELETE SET NULL,
    CONSTRAINT event_shopping_list_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_shopping_list_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_shopping_list_items REPLICA IDENTITY FULL;
ALTER TABLE public.event_shopping_list_items ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. Material Lists
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.event_material_lists (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    event_id text NOT NULL,
    name text NOT NULL,
    selected_menues text[] DEFAULT '{}'::text[] NOT NULL,
    selected_meals text[] DEFAULT '{}'::text[] NOT NULL,
    has_manually_added_items boolean DEFAULT false NOT NULL,
    firebase_uid text,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_material_lists_pkey PRIMARY KEY (id),
    CONSTRAINT event_material_lists_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT event_material_lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_material_lists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_material_lists REPLICA IDENTITY FULL;
ALTER TABLE public.event_material_lists ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.event_material_list_items (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    list_id text NOT NULL,
    material_id text,
    free_text_name text CONSTRAINT chk_material_free_text_name_length CHECK (char_length(free_text_name) <= 200),
    quantity numeric DEFAULT 0 NOT NULL,
    checked boolean DEFAULT false NOT NULL,
    edit_source public.shopping_list_edit_source DEFAULT 'generated'::public.shopping_list_edit_source NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    assigned_cook_id text,
    assigned_cook_name text,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT event_material_list_items_pkey PRIMARY KEY (id),
    CONSTRAINT chk_material_item_source CHECK (
      (material_id IS NOT NULL AND free_text_name IS NULL) OR
      (material_id IS NULL AND free_text_name IS NOT NULL)
    ),
    CONSTRAINT event_material_list_items_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.event_material_lists(id) ON DELETE CASCADE,
    CONSTRAINT event_material_list_items_material_id_fkey FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE SET NULL,
    CONSTRAINT event_material_list_items_assigned_cook_id_fkey FOREIGN KEY (assigned_cook_id) REFERENCES public.event_cooks(id) ON DELETE SET NULL,
    CONSTRAINT event_material_list_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT event_material_list_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.event_material_list_items REPLICA IDENTITY FULL;
ALTER TABLE public.event_material_list_items ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. Requests
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.requests (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    number integer DEFAULT nextval('public.request_number_seq'::regclass) NOT NULL,
    status public.request_status_type DEFAULT 'created'::public.request_status_type NOT NULL,
    request_type public.request_type_enum NOT NULL,
    author_uid uuid NOT NULL,
    assignee_uid uuid,
    request_object_uid text NOT NULL,
    change_log jsonb DEFAULT '[]'::jsonb NOT NULL,
    resolve_date timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT requests_pkey PRIMARY KEY (id),
    CONSTRAINT uq_requests_number UNIQUE (number),
    CONSTRAINT requests_author_uid_fkey FOREIGN KEY (author_uid) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT requests_assignee_uid_fkey FOREIGN KEY (assignee_uid) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT requests_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.requests IS 'Anträge (Rezept-Veröffentlichung, Fehlermeldungen)';
COMMENT ON COLUMN public.requests.number IS 'Fortlaufende Antragsnummer (via SEQUENCE)';
COMMENT ON COLUMN public.requests.request_object_uid IS 'UID des Rezepts, auf das sich der Antrag bezieht';
COMMENT ON COLUMN public.requests.change_log IS 'Statusänderungs-Protokoll als JSONB-Array [{date, userUid, action, newValue}]';

ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.request_comments (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    request_id text NOT NULL,
    comment text NOT NULL CONSTRAINT chk_comment_length CHECK (char_length(comment) <= 1000),
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT request_comments_pkey PRIMARY KEY (id),
    CONSTRAINT request_comments_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.requests(id) ON DELETE CASCADE,
    CONSTRAINT request_comments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT request_comments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.request_comments IS 'Kommentare zu Anträgen';
ALTER TABLE public.request_comments ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. Feeds
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.feeds (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    firebase_uid text,
    feed_type public.feed_type NOT NULL,
    visibility public.user_role DEFAULT 'basic'::public.user_role NOT NULL,
    user_uid uuid NOT NULL,
    source_object_type text NOT NULL CONSTRAINT chk_source_object_type_length CHECK (char_length(source_object_type) <= 200),
    source_object_uid text NOT NULL CONSTRAINT chk_source_object_uid_length CHECK (char_length(source_object_uid) <= 200),
    source_object_data jsonb,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT feeds_pkey PRIMARY KEY (id),
    CONSTRAINT feeds_user_uid_fkey FOREIGN KEY (user_uid) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT feeds_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT feeds_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.feeds IS 'Feed-Einträge für die Aktivitätsübersicht auf der Startseite.';
ALTER TABLE public.feeds ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 12. Donations
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.donations (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    event_id text,
    payrexx_gateway_id text,
    payrexx_reference_id text,
    payrexx_transaction_id text,
    amount_in_cents integer NOT NULL,
    currency text DEFAULT 'CHF'::text NOT NULL,
    status public.donation_status DEFAULT 'pending'::public.donation_status NOT NULL,
    payment_method text,
    paid_at timestamptz,
    donor_uid uuid NOT NULL,
    donor_message text,
    receipt_number text,
    receipt_sent_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT donations_pkey PRIMARY KEY (id),
    CONSTRAINT donations_receipt_number_key UNIQUE (receipt_number),
    CONSTRAINT donations_amount_in_cents_check CHECK (amount_in_cents > 0),
    CONSTRAINT donations_donor_message_check CHECK (char_length(donor_message) <= 200),
    CONSTRAINT donations_donor_uid_fkey FOREIGN KEY (donor_uid) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT donations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE SET NULL,
    CONSTRAINT donations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT donations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.donation_goal_sections (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    label text NOT NULL,
    target_cents integer NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    year integer DEFAULT (EXTRACT(year FROM now()))::integer NOT NULL,
    details text NOT NULL DEFAULT '',
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid DEFAULT auth.uid(),
    updated_at timestamptz DEFAULT now() NOT NULL,
    updated_by uuid DEFAULT auth.uid(),
    CONSTRAINT donation_goal_sections_pkey PRIMARY KEY (id),
    CONSTRAINT donation_goal_sections_target_cents_check CHECK (target_cents > 0),
    CONSTRAINT donation_goal_sections_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL,
    CONSTRAINT donation_goal_sections_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.donation_goal_sections ENABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────────────────────
-- 13. Admin / Monitoring
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.cron_job_log (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    job_name text NOT NULL,
    started_at timestamptz DEFAULT now() NOT NULL,
    finished_at timestamptz,
    status text DEFAULT 'running'::text NOT NULL,
    duration_ms integer,
    records_processed integer DEFAULT 0,
    error_message text,
    details jsonb,
    CONSTRAINT cron_job_log_pkey PRIMARY KEY (id)
);

ALTER TABLE public.cron_job_log ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.mail_log (
    id text DEFAULT (gen_random_uuid())::text NOT NULL,
    recipients jsonb DEFAULT '[]'::jsonb NOT NULL,
    recipient_type text DEFAULT 'email'::text NOT NULL,
    subject text DEFAULT ''::text NOT NULL,
    body text DEFAULT ''::text NOT NULL,
    template_name text,
    sent_at timestamptz DEFAULT now() NOT NULL,
    sent_by uuid DEFAULT auth.uid(),
    delivery_status text DEFAULT 'pending'::text NOT NULL,
    error_message text,
    details jsonb,
    CONSTRAINT mail_log_pkey PRIMARY KEY (id),
    CONSTRAINT mail_log_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.mail_log ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS internal.rpc_rate_limits (
    user_id       UUID NOT NULL,
    function_name TEXT NOT NULL,
    called_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
